---
# tasks file for ntp-svr package installation

- name: Install NTP server apt packages
  become: true
  apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  notify: start ntp
  with_items:
    - ntp

